SELECT * FROM sales_info;

-- 자동차 쿼리 작성
CREATE TABLE CAR_INFO (
	CAR_PK INT AUTO_INCREMENT PRIMARY KEY
	, CAR_NAME VARCHAR(30) NOT NULL
	, CAR_PRICE INT NOT NULL
	, CAR_BRAND VARCHAR (50) NOT NULL
);

CREATE TABLE SALES_INFO (
	SALES_PK INT AUTO_INCREMENT PRIMARY KEY
	, BUYER_NAME VARCHAR(30) NOT NULL
	, BUYER_TEL VARCHAR (50)
	, COLOR VARCHAR (50) NOT NULL
	, BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, CAR_PK INT NOT NULL REFERENCES CAR_INFO (CAR_PK) ON DELETE CASCADE
);

INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (1, '아반떼', 22000000, '현대');
INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (2, '쏘나타', 30000000, '현대');
INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (3, 'k3', 25000000, '기아');
INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (4, 'Qm6', 30000000, '르노');
INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (5, '더 비틀', 37000000, '폭스바겐');
INSERT INTO CAR_INFO (CAR_PK, CAR_NAME, CAR_PRICE, CAR_BRAND)
VALUE (6, 'e 클래스', 90000000, '벤츠');

SELECT * FROM CAR_INFO;
SELECT * FROM SALES_INFO;

INSERT INTO SALES_INFO (SALES_PK, BUYER_NAME, BUYER_TEL, COLOR, CAR_PK) 
VALUE (1, '현경', '010-5555-5555', '노란색', 5);
INSERT INTO SALES_INFO (SALES_PK, BUYER_NAME, BUYER_TEL, COLOR, CAR_PK) 
VALUE (2, '현경', '010-5555-5555', '콜드블루', 6);
INSERT INTO SALES_INFO (SALES_PK, BUYER_NAME, BUYER_TEL, COLOR, CAR_PK) 
VALUE (3, '노현경', '010-5555-7777', '흰색', 2);


