-- 테이블 삭제 (데이터 삭제와 잘 구분하여야한다)        ROLLBACK, COMMIT >> 안됨 삭제하면
DROP TABLE basic_board;    -- 테이블 삭제
DELETE FROM basic_borad;  -- 데이터 삭제

-- 게시판 프로그램 테이블 생성
CREATE TABLE BASIC_BOARD(
-- 컬럼명, 데이터타입, [제약조건들]         AUTO_INCREMENT(자동 증가)
BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
, TITLE VARCHAR(50) NOT NULL
, WRITER VARCHAR(50) NOT NULL 
, CONTENT VARCHAR(100) 
, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
, READ_CNT INT DEFAULT 0
);

INSERT INTO basic_board (TITLE, WRITER, CONTENT) 
VALUES ('1', '1', '1');

INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER)
VALUES (2, '제목', '작성자1');


SELECT * FROM basic_board;


INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT)
VALUES (1, '', '작성5', '내용AA', '2024-07-01', 5);
INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE)
VALUES (5, '', '작성55', '내용임', '2024-07-01');
INSERT INTO basic_board (BOARD_NUM, TITLE, WRITER, CONTENT, CREATE_DATE, READ_CNT)
VALUES (6, '오리날다', '미미', NULL, '2024-07-01', 3);

SELECT BOARD_NUM
, TITLE
, WRITER
, CREATE_DATE
, READ_CNT
FROM basic_board
WHERE TITLE LIKE '%안녕%';
WHERE WRITER LIKE '%java%'; 


SELECT * FROM basic_board;
